### ISSUE TITLE
System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.Byte'.

### ISSUE THREAD

**Issue by excelthoughts** [bchavez/Bogus#268]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |    26.0.2             |
| .NET Core?                   |       2.2          |
| .NET Full Framework?   |                 |
| Windows OS?              |           10       |
| Linux OS?                    |                  |
| Visual Studio?              |     2019    v16.3.7         |

### What locale are you using with Bogus?
English au
### What's the problem?
Have built up a complex Faker structure from EF POCOs. (over 450 lines of c#)
When it gets to final .Generate(), it throws System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.Byte'.

### What possible solutions have you considered?
Looked at all the rules to ensures the types are correct. eg
  .RuleFor(x => x.AccountId, x => x.Random.Int(1, 100000))
  .RuleFor(x => x.SuspensionPeriods, x => x.Random.Byte(1, 100))

### Do you have sample code to show what you're trying to do?
Sorry can't send == IP

I wonder whether there is a more verbose log so I can pinpoint the issue?

**Comment by excelthoughts** [comment]
Error Message:

Fi=000,Fa=000,Pe=001 #  1> SCENARIO: GetMembershipHandler success for only code
Fi=000,Fa=000,Pe=001 #  1>   STEP 1/3: GIVEN There is a Membership with id "1"...
Fi=000,Fa=000,Pe=001 #  1>   STEP 1/3: GIVEN There is a Membership with id "1" (Failed after 249ms)
Fi=001,Fa=001,Pe=000 #  1>   SCENARIO RESULT: Failed after 284ms
                               Step 1: System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.Byte'.
                               	at Bogus.Extensions.ExtensionsForPropertyInfo.<>c__DisplayClass2_0`2.<CreateSetterGeneric>b__0(T instance, Object value) in C:\projects\bogus\Source\Bogus\Extensions\ExtensionsForPropertyInfo.cs:line 31
                               	at Bogus.Faker`1.PopulateProperty(T instance, PopulateAction`1 action) in C:\projects\bogus\Source\Bogus\Faker[T].cs:line 597
                               	at Bogus.Faker`1.PopulateInternal(T instance, String[] ruleSets) in C:\projects\bogus\Source\Bogus\Faker[T].cs:line 545
                               	at Bogus.Faker`1.Generate(String ruleSets) in C:\projects\bogus\Source\Bogus\Faker[T].cs:line 427
                               	at HAMBS.Condor.Api.Member.Tests.v1.MembershipFeatureFixtureBase.GetFakeMembership(Int32 membershipId, DateTime effectiveDate) in D:\Source\Repos\Condor\test\HAMBS.Condor.Api.Member.Tests\v1\MembershipFeatureFixtureBase.cs:line 478
                               	at HAMBS.Condor.Api.Member.v1.Handlers.Memberships.Tests.GetMembershipHandlerTest.There_is_a_Membership_with_id(Int32 id) in D:\Source\Repos\Condor\test\HAMBS.Condor.Api.Member.Tests\v1\Handlers\Memberships\GetMembershipCommandHandlerTests.cs:line 73
                               	at lambda_method(Closure , NoContext , Object[] )
                               	at LightBDD.Core.Execution.Implementation.RunnableStep.RunStepAsync() in C:\projects\lightbdd\src\LightBDD.Core\Execution\Implementation\RunnableStep.cs:line 123
SCENARIO: GetMembershipHandler success for only code
  STEP 1/3: GIVEN There is a Membership with id "1"...
  STEP 1/3: GIVEN There is a Membership with id "1" (Failed after 249ms)
  SCENARIO RESULT: Failed after 284ms
    Step 1: System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.Byte'.
    	at Bogus.Extensions.ExtensionsForPropertyInfo.<>c__DisplayClass2_0`2.<CreateSetterGeneric>b__0(T instance, Object value) in C:\projects\bogus\Source\Bogus\Extensions\ExtensionsForPropertyInfo.cs:line 31
    	at Bogus.Faker`1.PopulateProperty(T instance, PopulateAction`1 action) in C:\projects\bogus\Source\Bogus\Faker[T].cs:line 597
    	at Bogus.Faker`1.PopulateInternal(T instance, String[] ruleSets) in C:\projects\bogus\Source\Bogus\Faker[T].cs:line 545
    	at Bogus.Faker`1.Generate(String ruleSets) in C:\projects\bogus\Source\Bogus\Faker[T].cs:line 427
    	at HAMBS.Condor.Api.Member.Tests.v1.MembershipFeatureFixtureBase.GetFakeMembership(Int32 membershipId, DateTime effectiveDate) in D:\Source\Repos\Condor\test\HAMBS.Condor.Api.Member.Tests\v1\MembershipFeatureFixtureBase.cs:line 478
    	at HAMBS.Condor.Api.Member.v1.Handlers.Memberships.Tests.GetMembershipHandlerTest.There_is_a_Membership_with_id(Int32 id) in D:\Source\Repos\Condor\test\HAMBS.Condor.Api.Member.Tests\v1\Handlers\Memberships\GetMembershipCommandHandlerTests.cs:line 73
    	at lambda_method(Closure , NoContext , Object[] )
    	at LightBDD.Core.Execution.Implementation.RunnableStep.RunStepAsync() in C:\projects\lightbdd\src\LightBDD.Core\Execution\Implementation\RunnableStep.cs:line 123

**Comment by excelthoughts** [comment]
dumb code issue
