### ISSUE TITLE
Automatic conversion

### ISSUE THREAD

**Issue by gsscoder** [bchavez/Bogus#280]
Even if the following code raise an **exception** I see this issue more as feature request than other.
If I write a rule for a numeric property a conversion error may occur.
It's more easy to see the code:
```csharp
class Foo
{
    public string Baz;
    public int Bar;
    public ushort Boo; 
}
var foo = new Faker<Foo>()
    .RuleFor(o => o.Baz, f => f.Hacker.Phrase())
    .RuleFor(o => o.Bar, f => f.PickRandom(10, 20, 30))
    .RuleFor(o => o.Boo, f => f.PickRandom(40, 50, 60))
    .Generate();
```
The following exception:
```
Unhandled exception. System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.UInt16'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at Bogus.Faker`1.<>c__DisplayClass55_0.<PopulateProperty>b__0(T i, Object v)
   at Bogus.Faker`1.PopulateProperty(T instance, PopulateAction`1 action)
   at Bogus.Faker`1.PopulateInternal(T instance, String[] ruleSets)
   at Bogus.Faker`1.Generate(String ruleSets)
   at Program.Main(String[] args) in /Users/coder/Dropbox/Hacking/DotNetCore/bogusunsigned/Program.cs:line 18
coder@macbook-pro bogusunsigned % git commit -am "Added ServiceType info to ResultHandledEventArgs"
fatal: not a git repository (or any of the parent directories): .git
coder@macbook-pro bogusunsigned % dotnet run                                                       
Program.cs(9,16): warning CS0649: Non è possibile assegnare un valore diverso al campo 'Foo.Bar'. Il valore predefinito è 0. [/Users/coder/Dropbox/Hacking/DotNetCore/bogusunsigned/BogusUnsigned.csproj]
Program.cs(7,19): warning CS0649: Non è possibile assegnare un valore diverso al campo 'Foo.Baz'. Il valore predefinito è null. [/Users/coder/Dropbox/Hacking/DotNetCore/bogusunsigned/BogusUnsigned.csproj]
Program.cs(11,19): warning CS0649: Non è possibile assegnare un valore diverso al campo 'Foo.Boo'. Il valore predefinito è 0. [/Users/coder/Dropbox/Hacking/DotNetCore/bogusunsigned/BogusUnsigned.csproj]
Unhandled exception. System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.UInt16'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at Bogus.Faker`1.<>c__DisplayClass55_0.<PopulateProperty>b__0(T i, Object v)
   at Bogus.Faker`1.PopulateProperty(T instance, PopulateAction`1 action)
   at Bogus.Faker`1.PopulateInternal(T instance, String[] ruleSets)
   at Bogus.Faker`1.Generate(String ruleSets)
   at Program.Main(String[] args) in /Users/coder/Dropbox/Hacking/DotNetCore/bogusunsigned/Program.cs:line 18
```
is raised because no automatic conversion is made from `int` to `ushort`. The same happens using a constant expression: `_ => 10`.

The alternative is calling `PickRandom<ushort>` or casting the constant `(ushort)10`.

Since an `int` of value `10` con be converted into an `ushort`, it would be nice to see this happens automatically.

Thank you for great project!

**Comment by bchavez** [comment]
Hi Giacomo,

Thanks very much for the suggestion. My apologies for the late reply. I've been working on some deep investigations into #279; the result of which carries some possible improvements to `Faker<T>`. Also, I read your issue some days ago, during the delay in my reply here, I was able to think more about this situation.

I agree it would be helpful to have some automatic conversion in this scenario. However, I get a cautionary feeling about baking automatic conversion into `Faker<T>` by ***default***. I think this feeling is rooted in the same reasons why the C# type system won't convert an `int` to `ushort` out of the box.

I think you might already know about adding too many "automagical" things in APIs. By keeping `Faker<T>` simple, and straight-forward, and "close to the metal"; there's no "middle layer" interfering with your values.

It's a difficult balance to strike between easing developer friction and unexpected supprises (due to assumptions being made under the hood). This is one reason why I've opened up much of the `Faker<T>` internals to derived types so that behavior can be modified on a case-by-case basis.

For now, the approach I'd like to suggest is hooking the value generation in a derived type of `Faker<T>`. The following unit test passes with `MagicFaker<T>`:

```csharp
[Fact]
public void custom_faker_with_automatic_conversion_does_not_throw()
{
   var fooFaker = new MagicFaker<Foo>()
      .RuleFor(o => o.Baz, f => f.Hacker.Phrase())
      .RuleFor(o => o.Bar, f => f.PickRandom(10, 20, 30))
      .RuleFor(o => o.Boo, f => f.PickRandom(40, 50, 60));

   var foo = fooFaker.Generate();

   foo.Baz.Should().Be("Use the neural RAM driver, then you can calculate the neural driver!");
   foo.Bar.Should().Be(10);
   foo.Boo.Should().Be(60);
}
```
```csharp
// C# 8.0 used
public class MagicFaker<T> : Faker<T> where T : class
{
   protected override Faker<T> AddRule(string propertyOrField, Func<Faker, T, object> invoker)
   {
      Func<Faker, T, object> hook = (faker, t) =>
         {
            var initialValue = invoker(faker, t);
            return ConvertValue(propertyOrField, initialValue);
         };
      return base.AddRule(propertyOrField, hook);
   }

   private object ConvertValue(string propertyOrField, object initialValue)
   {
      if( initialValue is null ) return null;

      if( !this.TypeProperties.TryGetValue(propertyOrField, out var memberInfo) )
         return initialValue;

      var targetType = memberInfo switch
         {
            PropertyInfo pi => pi.PropertyType,
            FieldInfo fi => fi.FieldType,
            _ => throw new Exception("Unknown reflection type.")
         };

      var convertedValue = targetType switch
         {
            Type t when t == typeof(int) => Convert.ToInt32(initialValue),
            Type t when t == typeof(uint) => Convert.ToUInt32(initialValue),
            Type t when t == typeof(long) => Convert.ToInt64(initialValue),
            Type t when t == typeof(ulong) => Convert.ToUInt64(initialValue),
            Type t when t == typeof(short) => Convert.ToInt16(initialValue),
            Type t when t == typeof(ushort) => Convert.ToUInt16(initialValue),
            Type t when t == typeof(float) => Convert.ToSingle(initialValue),
            Type t when t == typeof(double) => Convert.ToDouble(initialValue),
            Type t when t == typeof(decimal) => Convert.ToDecimal(initialValue),
            Type t when t == typeof(byte) => Convert.ToByte(initialValue),
            Type t when t == typeof(sbyte) => Convert.ToSByte(initialValue),
            Type t when t == typeof(bool) => Convert.ToBoolean(initialValue),
            Type t when t == typeof(char) => Convert.ToChar(initialValue),
            _ => initialValue
         };

      return convertedValue;
   }
}
```
Full code and unit tests can be found here: https://github.com/bchavez/Bogus/blob/76c07f040fa91c78a69b5a991e60f9d00d8b7ca7/Source/Bogus.Tests/GitHubIssues/Issue280.cs#L1

I'm going to close the issue for now, but please feel free to carry on the conversation. I'd like to know if you think this solution is acceptable and any other thoughts you might have. Also, I will keep an open mind if other's have the same issue. Usually when I get more than one request for a feature or change then I start reconsidering making changes.

Thanks,
Brian

**Comment by gsscoder** [comment]
@bchavez,
no need to apologize for reply times. Instead I need to thank you on how much is exhaustive!
I'm agree to not add too _magic_ into **API**s.

The `AddRule` machinery you illustrate is very interesting.

**Bogus** is already mature and robust and this thing is marginal. I just posted here to give my little contribute.

Have a nice day!
