### ISSUE TITLE
OverflowException for random ulong

### ISSUE THREAD

**Issue by reuterma24** [bchavez/Bogus#581]
### Bogus NuGet Package

v35.6.1

### .NET Version

.NET 8

### What operating system are you using?

MacOS

### What locale are you using with Bogus?

en

### Problem Description

Hi everbody! 😃 

I just stumbled across an issue with the [ULong method](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Randomizer.cs#L272).
According to the documentation, it generates a random `ulong` between `ulong.MinValue` and `ulong.MaxValue`.
Unfortunately the method crashes due to an arithmetic overflow if the `min` parameter is very large (relatively close to MaxValue).

### LINQPad Example or Reproduction Steps

The following test case will fail and trigger the overflow:

```csharp
[Fact]
public void overflow_test()
{
    var randomizer = new Randomizer();
    ulong max = ulong.MaxValue;
    ulong min = max - 10; // I could go up to -3000 on my machine
    
    ulong result = randomizer.ULong(min, max);
  
    result.Should().BeInRange(min, max);
}
```

### Expected Behavior

Expected would be a random ulong in the desired range instead of a crash.

### Actual Behavior

Actual implementation:

```csharp
public ulong ULong(ulong min = ulong.MinValue, ulong max = ulong.MaxValue)
{
    return Convert.ToUInt64(Double() * (max - min) + min);
}
```

```
Stacktrace:
Failed Bogus.Tests.RandomizerTest.overflow_test [5 ms]
  Error Message:
   System.OverflowException : Arithmetic operation resulted in an overflow.
  Stack Trace:
     at System.Convert.ToUInt64(Double value)
   at Bogus.Randomizer.ULong(UInt64 min, UInt64 max)
```

Altough I am not an expert on this, I believe it happens because of _floating-point rounding_.

- The `Double()` method generates a random value between 0 and 1.
- When multiplied by `(max - min)` — in this case, 10 — it produces a small double with many decimal places
(like 6.5668499183687 for example).
- Adding the very large `min` value (`Double() * (max - min) + min`) results in a value where the mantissa cannot accurately represent the least significant bits, causing it to round up and exceed `ulong.MaxValue`.

### Known Workarounds

I think a very simple way of fixing this and avoiding the rounding error is to convert the randomized `double` to a `ulong` before adding `min`, just like this:

```csharp
public ulong ULong(ulong min = ulong.MinValue, ulong max = ulong.MaxValue)
{
    return Convert.ToUInt64(Double() * (max - min)) + min;
}
```

This implementation also passes all test cases inside [RandomizerTest.cs](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/RandomizerTest.cs).

### Could you help with a pull-request?

Yes

**Comment by bchavez** [comment]
Hi. Thanks a bunch for the suggested fix. Should be in #585; and hopefully have a release shortly.
